
development:
  adapter: mysql2
  database: xmolexam
  host: 127.0.0.1
  username: root
  password: ergal1234
  encoding: utf8

test:
  adapter: mysql2
  database: xmolexam_test
  username: root
  password: ergal1234
  encoding: utf8

production:
  adapter: mysql2
  database: xmolexam_production
  username: root
  password: ergal1234
  encoding: utf8
